# configuration flags to customize site

# Name of your site (displayed in the header)
name: Stella Wang

# Short bio or description (displayed in the header)
description: An engineering student with little time & BIG ideas. 

# URL my GitHub profile pic
avatar: https://avatars0.githubusercontent.com/u/46392676?s=460&v=4

# Tabs in header and URL Link
navigation:
  - name: Blog
    url: /blog
  - name: Projects
    url: /projects
  - name: Resume
    url: /resume.pdf
  - name: About
    url: /about

# Pagination
# paginate: 20
# permalink: /:title/
# paginate_path: /blog/page:num/
# sort_field: 'date'

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: stella.wang@alumni.ubc.ca
  facebook: stella01wang
  flickr:
  github: stellaw1/stellaw1.github.io
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram: stellaw__
  linkedin: stella01wang
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: 
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: © 2020 Stella Wang

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # <username>.disqus.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-V2B6DPYDLE

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:


# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji 

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
